#!/usr/bin/env bash
#
# deploy_dashboard.sh — upload the landing page and the Qt WebAssembly
# dashboard build to the EC2 Apache docroot. Apache is assumed already
# installed and configured (vhost + headers); this ships files, fixes
# permissions, makes sure the vhost serves the landing page at "/", and
# verifies.
#
# Site layout after a deploy:
#   /                       landing page (index.html, from ./web)
#   /SensorDashboard.html   the WebAssembly dashboard, linked from it
#
# The .html/.js/.wasm come from the build directory; index.html and
# config.json come from the tracked sources, so editing config.json and
# redeploying works without a rebuild.
#
# Usage:
#   ./deploy_dashboard.sh
#   ./deploy_dashboard.sh -i ~/keys/ArashLinux.pem
#   ./deploy_dashboard.sh -b /path/to/WebAssembly_..._Release -H 1.2.3.4
#   ./deploy_dashboard.sh -n            # skip the vhost DirectoryIndex step
#
# Config precedence: CLI flag > env var > built-in default.

set -euo pipefail

# ── Defaults (override via env or flags) ───────────────────────────
PEM="${DASH_PEM:-./ArashLinux.pem}"
REMOTE_HOST="${DASH_HOST:-ec2-54-213-147-59.us-west-2.compute.amazonaws.com}"
REMOTE_USER="${DASH_USER:-ubuntu}"
DOCROOT="${DASH_DOCROOT:-/home/ubuntu/dashboard}"
# The default embeds a Qt version and threading mode, because that is
# what Qt Creator names the directory. A different machine or kit will
# name it differently, so treat this as a hint: if it doesn't exist and
# nothing was passed explicitly, the pre-flight globs ./build for a
# WebAssembly release directory instead.
BUILD_DIR="${DASH_BUILD:-./build/WebAssembly_Qt_6_8_2_single_threaded-Release}"
BUILD_DIR_EXPLICIT=0
[[ -n "${DASH_BUILD:-}" ]] && BUILD_DIR_EXPLICIT=1
SRC_DIR="${DASH_SRC:-.}"
VHOST="${DASH_VHOST:-/etc/apache2/sites-available/dashboard.conf}"
SSH_PORT="${DASH_PORT:-22}"
SKIP_VHOST="${DASH_SKIP_VHOST:-0}"

# Generated by the WebAssembly build. qtlogo.svg is referenced by the
# generated loader page.
REQUIRED_FILES=(
    "SensorDashboard.html"
    "SensorDashboard.js"
    "SensorDashboard.wasm"
    "qtloader.js"
)
OPTIONAL_FILES=(
    "qtlogo.svg"
)

# Tracked source files, taken from SRC_DIR rather than the build tree
# and flattened into the docroot by basename.
#
# config.json is deliberately NOT read from the build directory. qmake
# copies it there on every build, but the whole point of the file is
# that sensors and colours can be changed without recompiling — so a
# deploy that follows an edit but no rebuild would ship the stale build
# copy. Shipping the tracked file makes it the single source of truth.
SITE_FILES=(
    "web/index.html"
    "config.json"
)

# ── Parse flags ────────────────────────────────────────────────────
usage() {
    sed -n '2,23p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

while getopts "i:H:u:d:b:s:v:P:nh" opt; do
    case "$opt" in
        i) PEM="$OPTARG" ;;
        H) REMOTE_HOST="$OPTARG" ;;
        u) REMOTE_USER="$OPTARG" ;;
        d) DOCROOT="$OPTARG" ;;
        b) BUILD_DIR="$OPTARG"; BUILD_DIR_EXPLICIT=1 ;;
        s) SRC_DIR="$OPTARG" ;;
        v) VHOST="$OPTARG" ;;
        P) SSH_PORT="$OPTARG" ;;
        n) SKIP_VHOST=1 ;;
        h) usage 0 ;;
        *) usage 1 ;;
    esac
done

TARGET="${REMOTE_USER}@${REMOTE_HOST}"
SSH_OPTS=(-i "$PEM" -p "$SSH_PORT")
SCP_OPTS=(-i "$PEM" -P "$SSH_PORT")   # note: scp uses -P (capital) for port

# ── Pre-flight checks (local) ──────────────────────────────────────
echo "==> Pre-flight checks"

if [[ ! -f "$PEM" ]]; then
    echo "ERROR: PEM key not found: $PEM" >&2
    echo "       Pass it with -i /path/to/key.pem or set DASH_PEM." >&2
    exit 1
fi

# SSH refuses keys with loose permissions; fix quietly if needed.
perms=$(stat -c "%a" "$PEM" 2>/dev/null || stat -f "%A" "$PEM" 2>/dev/null || echo "")
if [[ "$perms" != "600" && "$perms" != "400" ]]; then
    echo "    Tightening PEM permissions to 600 (was ${perms:-unknown})"
    chmod 600 "$PEM"
fi

# Fall back to discovery when the version-stamped default is wrong,
# which it will be on any machine whose Qt kit differs from the one the
# default was written for.
if [[ ! -d "$BUILD_DIR" && "$BUILD_DIR_EXPLICIT" -eq 0 ]]; then
    shopt -s nullglob
    candidates=(./build/*WebAssembly*[Rr]elease*/)
    shopt -u nullglob
    if [[ "${#candidates[@]}" -eq 1 ]]; then
        BUILD_DIR="${candidates[0]%/}"
        echo "    Default build dir absent; using discovered $BUILD_DIR"
    elif [[ "${#candidates[@]}" -gt 1 ]]; then
        echo "ERROR: several WebAssembly build directories under ./build:" >&2
        printf '         %s\n' "${candidates[@]%/}" >&2
        echo "       Pick one with -b <dir>." >&2
        exit 1
    fi
fi

if [[ ! -d "$BUILD_DIR" ]]; then
    echo "ERROR: Build directory not found: $BUILD_DIR" >&2
    echo "       Build the WebAssembly target first, or pass -b <dir>." >&2
    exit 1
fi

missing=0
for f in "${REQUIRED_FILES[@]}"; do
    if [[ ! -f "$BUILD_DIR/$f" ]]; then
        echo "ERROR: required file missing from build: $f" >&2
        missing=1
    fi
done
if [[ "$missing" -ne 0 ]]; then
    echo "       Did the WebAssembly build complete successfully?" >&2
    exit 1
fi
echo "    All required files present in $BUILD_DIR"

for f in "${SITE_FILES[@]}"; do
    if [[ ! -f "$SRC_DIR/$f" ]]; then
        echo "ERROR: source file missing: $SRC_DIR/$f" >&2
        echo "       This is a tracked source file, not a build artifact." >&2
        echo "       Run from the FrontEnd directory, or pass -s <dir>." >&2
        exit 1
    fi
done
echo "    Source files present in $SRC_DIR"

# ── Connectivity check ─────────────────────────────────────────────
echo "==> Testing SSH connection to $TARGET:$SSH_PORT"
if ! ssh "${SSH_OPTS[@]}" -o ConnectTimeout=10 -o BatchMode=yes "$TARGET" "true" 2>/dev/null; then
    echo "ERROR: cannot SSH to $TARGET" >&2
    echo "       Check the host, the PEM, and that your IP is allowed on port $SSH_PORT." >&2
    exit 1
fi
echo "    SSH OK"

# ── Ensure docroot exists ──────────────────────────────────────────
echo "==> Ensuring docroot exists: $DOCROOT"
ssh "${SSH_OPTS[@]}" "$TARGET" "mkdir -p '$DOCROOT'"

# ── Upload ─────────────────────────────────────────────────────────
# Upload to a temp dir first, then move into place, so a half-finished
# transfer can't leave the live site serving a broken mix of old/new.
STAMP="$(date +%Y%m%d-%H%M%S)"
STAGING="/tmp/dashboard-upload-$STAMP"
echo "==> Uploading build to staging ($STAGING)"
ssh "${SSH_OPTS[@]}" "$TARGET" "mkdir -p '$STAGING'"

# The generated loader page needs one patch before it goes up. Qt's stock
# template leaves #screen at display:none while qtLoad() runs, so Qt sizes its
# canvas against a zero-height container and paints nothing — the page stays
# blank until some unrelated window resize (famously, opening devtools) makes
# Qt re-read the size. Dispatching a resize ourselves once the canvas is
# actually visible removes that. Patched here rather than in the build tree
# because Qt regenerates this file on every rebuild.
PATCHED_HTML=""
patch_loader() {
    local src="$1"
    PATCHED_HTML="$(mktemp -t sensordashboard-XXXXXX.html)"
    python3 - "$src" "$PATCHED_HTML" <<'PYEOF'
import sys
src, dst = sys.argv[1], sys.argv[2]
page = open(src).read()

# Qt's stock showUi() sets the container (#screen) to display:none while the
# loading spinner is up. The WASM platform plugin measures that container to
# size its canvas, and a display:none element measures 0x0 — so Qt builds a
# zero-size canvas and paints nothing. Revealing the container afterwards does
# not make Qt re-measure, which is why the page stayed blank until an unrelated
# window resize (opening devtools) forced one.
#
# Rather than trying to trigger a re-measure, keep the container laid out for
# the whole load and overlay the spinner on top of it.
old_showui = """            const showUi = (ui) => {
                [spinner, screen].forEach(element => element.style.display = 'none');
                if (screen === ui)
                    screen.style.position = 'default';
                ui.style.display = 'block';
            }"""
new_showui = """            const showUi = (ui) => {
                // Never display:none the Qt container — it is measured to size
                // the canvas, and a hidden element measures 0x0. Keep it laid
                // out and show/hide the overlaid loading screen instead.
                screen.style.display = 'block';
                spinner.style.display = (ui === spinner) ? 'block' : 'none';
            }"""

if old_showui not in page:
    print("    !! showUi() not in the expected form — shipping unpatched", file=sys.stderr)
    open(dst, "w").write(page)
    sys.exit(0)
page = page.replace(old_showui, new_showui, 1)

# Float the loading screen above the canvas now that both are laid out.
page = page.replace(
    "#screen { width: 100%; height: 100%; }",
    "#screen { width: 100%; height: 100%; }\n"
    "      #qtspinner {\n"
    "        position: fixed; inset: 0; z-index: 9999; margin: 0;\n"
    "        background: #fff; overflow: auto;\n"
    "      }", 1)

open(dst, "w").write(page)
print("    (patched: container stays laid out, loading screen overlaid)")
PYEOF
}

for f in "${REQUIRED_FILES[@]}"; do
    echo "    -> $f"
    if [[ "$f" == *.html ]]; then
        patch_loader "$BUILD_DIR/$f"
        scp "${SCP_OPTS[@]}" -q "$PATCHED_HTML" "$TARGET:$STAGING/$f"
        rm -f "$PATCHED_HTML"
    else
        scp "${SCP_OPTS[@]}" -q "$BUILD_DIR/$f" "$TARGET:$STAGING/$f"
    fi
done
for f in "${OPTIONAL_FILES[@]}"; do
    if [[ -f "$BUILD_DIR/$f" ]]; then
        echo "    -> $f (optional)"
        scp "${SCP_OPTS[@]}" -q "$BUILD_DIR/$f" "$TARGET:$STAGING/$f"
    fi
done
for f in "${SITE_FILES[@]}"; do
    echo "    -> $f (source)"
    scp "${SCP_OPTS[@]}" -q "$SRC_DIR/$f" "$TARGET:$STAGING/$(basename "$f")"
done

# ── Move into place + permissions ──────────────────────────────────
# 644 for files so Apache (and the world) can read them; the docroot
# itself needs 755 so Apache can traverse it (matches the guide's note
# about 403s otherwise). Only top-level files are chmod'ed — a blanket
# 644 on a subdirectory would make it untraversable.
echo "==> Moving into docroot and setting permissions"
ssh "${SSH_OPTS[@]}" "$TARGET" "
    set -e
    cp -f '$STAGING'/* '$DOCROOT'/
    chmod 755 '$DOCROOT'
    find '$DOCROOT' -maxdepth 1 -type f -exec chmod 644 {} +
    rm -rf '$STAGING'
"

# ── Make Apache serve the landing page at "/" ──────────────────────
# The vhost from the deployment guide sets "DirectoryIndex
# SensorDashboard.html", which sends "/" straight to the charts. Put
# index.html first so the landing page is the entry point; keep the old
# value as a fallback so the site still works if index.html is ever
# missing. Idempotent: a vhost already listing index.html is left alone.
if [[ "$SKIP_VHOST" -eq 1 ]]; then
    echo "==> Skipping vhost DirectoryIndex step (-n)"
else
    echo "==> Ensuring DirectoryIndex serves index.html first"
    set +e
    ssh "${SSH_OPTS[@]}" "$TARGET" "
        set -e
        if [ ! -f '$VHOST' ]; then
            echo '    vhost not found: $VHOST'
            exit 10
        fi
        if grep -qE '^[[:space:]]*DirectoryIndex[[:space:]]+index\.html' '$VHOST'; then
            echo '    Already correct — no change'
            exit 0
        fi
        if ! sudo -n true 2>/dev/null; then
            echo '    No passwordless sudo available'
            exit 11
        fi
        sudo cp -n '$VHOST' '$VHOST.bak' 2>/dev/null || true
        if grep -qE '^[[:space:]]*DirectoryIndex[[:space:]]' '$VHOST'; then
            sudo sed -i -E \
                's|^([[:space:]]*)DirectoryIndex[[:space:]].*|\1DirectoryIndex index.html SensorDashboard.html|' \
                '$VHOST'
        else
            sudo sed -i -E \
                's|^([[:space:]]*)DocumentRoot[[:space:]].*|&\n\1DirectoryIndex index.html SensorDashboard.html|' \
                '$VHOST'
        fi
        # Capture rather than pipe: piping into tail would make the
        # pipeline's status tail's, and a broken config would sail past.
        if ! out=\$(sudo apache2ctl configtest 2>&1); then
            echo \"\$out\"
            echo '    configtest FAILED — restoring backup'
            sudo cp '$VHOST.bak' '$VHOST'
            exit 12
        fi
        sudo systemctl reload apache2
        echo '    DirectoryIndex updated and Apache reloaded'
    "
    vhost_rc=$?
    set -e
    if [[ "$vhost_rc" -ne 0 ]]; then
        echo "    WARNING: could not update the vhost automatically (exit $vhost_rc)." >&2
        echo "    Run this on $REMOTE_HOST yourself, then re-run with -n:" >&2
        echo "      sudo sed -i 's|^\\(\\s*\\)DirectoryIndex .*|\\1DirectoryIndex index.html SensorDashboard.html|' $VHOST" >&2
        echo "      sudo apache2ctl configtest && sudo systemctl reload apache2" >&2
    fi
fi

# ── Verify ─────────────────────────────────────────────────────────
echo "==> Verifying deployment over HTTP"
BASE="http://$REMOTE_HOST"

check_url() {
    local path="$1" expect_type="$2"
    local code ctype label
    label="${path:-/ (index)}"
    code=$(curl -s -o /dev/null -w "%{http_code}" "$BASE/$path" || echo "000")
    ctype=$(curl -s -o /dev/null -w "%{content_type}" "$BASE/$path" || echo "")
    printf "    %-22s HTTP %s  %s\n" "$label" "$code" "$ctype"
    if [[ "$code" != "200" ]]; then
        echo "      WARNING: expected 200 for $path" >&2
        return 1
    fi
    if [[ -n "$expect_type" && "$ctype" != *"$expect_type"* ]]; then
        echo "      WARNING: expected content-type containing '$expect_type'" >&2
    fi
    return 0
}

rc=0
check_url ""                     "text/html"         || rc=1
check_url "index.html"           "text/html"         || rc=1
check_url "SensorDashboard.html" "text/html"        || rc=1
check_url "SensorDashboard.wasm" "application/wasm"  || rc=1
check_url "SensorDashboard.js"   ""                  || rc=1
check_url "qtloader.js"          ""                  || rc=1
check_url "config.json"          "json"              || rc=1

# A 200 at "/" isn't enough: if DirectoryIndex still points only at
# SensorDashboard.html, the root serves the charts and looks fine. Check
# that the body is actually the landing page.
echo "==> Checking that / serves the landing page"
root_body=$(curl -s "$BASE/" || echo "")
if grep -q 'href="SensorDashboard.html"' <<<"$root_body"; then
    echo "    / serves the landing page"
else
    echo "    WARNING: / does not look like the landing page — DirectoryIndex" >&2
    echo "             is probably still pointing at SensorDashboard.html." >&2
    rc=1
fi

echo
if [[ "$rc" -eq 0 ]]; then
    echo "Deploy complete."
    echo "  Landing page: $BASE/"
    echo "  Dashboard:    $BASE/SensorDashboard.html"
    echo "  (hard-refresh: Ctrl+Shift+R)"
else
    echo "Deploy finished with warnings — check the messages above." >&2
    echo "Common causes: .wasm MIME not set (AddType application/wasm .wasm)," >&2
    echo "DirectoryIndex not updated, or docroot/file permissions." >&2
    echo "See the deployment guide §9.1." >&2
fi
exit "$rc"
